add_dracutmodules+=" nabu-release-policy "
omit_drivers+=" scsi_debug "
install_items+=" /usr/lib/firmware/regulatory.db /usr/lib/firmware/qcom/a630_sqe.fw /usr/lib/firmware/qcom/a640_gmu.bin /usr/lib/firmware/qcom/sm8150/xiaomi/nabu/a640_zap.mbn /usr/lib/firmware/novatek/novatek_nt36523_fw.bin /usr/lib/firmware/qca/crbtfw32.tlv.xz /usr/lib/firmware/qca/crnv32.bin.xz "
