[Greeter]
ShowClock=true
WallpaperPluginId=org.kde.image

[Greeter][Wallpaper][org.kde.image][General]
Image=file:///usr/share/backgrounds/nabu/nabu-plasma-login.svg
PreviewImage=file:///usr/share/backgrounds/nabu/nabu-plasma-login.svg
