[Unit]
Wants=mnt-vendor-persist.mount
Wants=hexagonrpcd-sdsp.service
After=mnt-vendor-persist.mount
After=hexagonrpcd-sdsp.service

[Service]
# hexagonrpcd is Type=simple and the downstream SSC firmware can take several
# seconds to publish its QRTR service after the file listener starts.
ExecStartPre=/usr/bin/sleep 10

[Install]
WantedBy=multi-user.target
