context.properties = {
    log.level = 0
}

context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}

context.modules = [
    { name = libpipewire-module-rt flags = [ ifexists nofail ] }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Nabu Screen-relative Speakers"
            media.name = "Nabu four-speaker stereo fan-out"
            filter.graph = {
                nodes = [
                    { type = builtin name = input_left  label = copy }
                    { type = builtin name = input_right label = copy }
                    { type = builtin name = front_left  label = copy }
                    { type = builtin name = front_right label = copy }
                    { type = builtin name = rear_left   label = copy }
                    { type = builtin name = rear_right  label = copy }
                ]
                links = [
                    { output = "input_left:Out"  input = "front_left:In" }
                    { output = "input_left:Out"  input = "rear_left:In" }
                    { output = "input_right:Out" input = "front_right:In" }
                    { output = "input_right:Out" input = "rear_right:In" }
                ]
                inputs = [ "input_left:In" "input_right:In" ]
                outputs = [
                    "front_left:Out"
                    "front_right:Out"
                    "rear_left:Out"
                    "rear_right:Out"
                ]
            }
            capture.props = {
                node.name = "nabu_screen_speakers"
                node.description = "Nabu Screen-relative Speakers"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                priority.session = 2000
            }
            playback.props = {
                node.name = "playback.nabu_screen_speakers"
                media.class = "Stream/Output/Audio"
                audio.position = [ FL FR RL RR ]
                node.autoconnect = false
                node.dont-reconnect = true
                stream.dont-remix = true
                node.passive = true
            }
        }
    }
]
