[UKI]
Cmdline=root=PARTLABEL=linux rootfstype=ext4 ro rootwait rd.retry=30 deferred_probe_timeout=0 fw_devlink=permissive systemd.gpt_auto=no quiet splash fbcon=rotate:1 fbcon=font:TER16x32 selinux=1 enforcing=1
Stub=/usr/lib/systemd/boot/efi/linuxaa64.efi.stub
